name: Builder for Home Assistant Dispatcharr addon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dispatcharr (${{ matrix.arch }})
    strategy:
      matrix:
        arch: ["amd64", "aarch64", "armv7"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dispatcharr
        uses: home-assistant/builder@2024.03.5
        with:
          args: |
            --${{ matrix.arch }} \
            --target . \
            --image "ghcr.io/${{ github.repository_owner }}/addon-dispatcharr-${{ matrix.arch }}" \
            --addon
            --image "ghcr.io/${{ github.repository_owner }}/addon-dispatcharr-${{ matrix.arch }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
